#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'

xsetroot -cursor_name left_ptr &

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color3"
bspc config focused_border_color "$color7"

sh ~/.fehbg
$HOME/.config/polybar/polybar.sh
